# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#*****引入Flutter*****
# 注意此处的路径，因为此项目为demo，所以写的相对路径
# flutter_application_path = '../flutter_ios_module'
# load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
# 在target中，需要加入：
# install_all_flutter_pods(flutter_application_path)
#********************

flutter_application_path = '../flutter_ios_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

platform :ios, '9.0'

target 'NativeToFlutterDemo' do
  install_all_flutter_pods(flutter_application_path)
  use_frameworks!

  # Pods for NativeToFlutterDemo
  target 'NativeToFlutterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeToFlutterDemoUITests' do
    # Pods for testing
  end

end
